# Generated by Django 5.2.1 on 2025-05-12 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_agents', models.IntegerField()),
                ('num_wastes', models.IntegerField()),
                ('base_position_x', models.IntegerField()),
                ('base_position_y', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waste_collected', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
                ('turn_number', models.IntegerField(default=-1)),
                ('_waste_positions', models.TextField(blank=True, default='[]')),
                ('_agent_positions', models.TextField(blank=True, default='[]')),
                ('_known_waste_positions', models.TextField(blank=True, default='[]')),
                ('configuration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game', to='walle.configuration')),
            ],
        ),
    ]
